#!/bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         0
bspc config window_gap          37

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus       true
bspc config urgent_border_color "#72003e"

xsetroot -cursor_name left_ptr &
redshift -l 39.866397:-83.074054 &
xrdb ~/.Xresources/secondsun
feh --bg-fill ~/Downloads/secondsun.png
btops &
polybar main &
light -S 5 &
xss-lock -- lock
