#!/bin/dash

rectangles=" "

SR=$(xrandr --query | grep ' connected' | grep -o 'x[0-9][0-9]*')
for RES in $SR; do
	SRA=$(echo ${RES} | sed -e "s|x||g")
	CX=37
	CY=$((SRA - 37))
	rectangles="rectangle $CX,$CY $((CX+300)),$((CY-80)) "${rectangles}
done

TMPBG=$(cat ~/.fehbg)
TMPBG=$(echo ${TMPBG} | sed -e "s|#\!/bin/sh||g" | sed -e "s|'||g" | sed -e "s|feh --bg-fill||g")

cp $TMPBG /tmp/screen
convert /tmp/screen -resize 1920x1080 -draw "fill black fill-opacity 0.4 $rectangles" /tmp/screen
